name:                Haskell-Experiments
version:             0.1.0.0
github:              "Bertrand31/Haskell-Experiments"
license:             GPLv3
author:              "Bertrand Junqua"
maintainer:          "example@example.com"
copyright:           "2020 Bertrand Junqua"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Haskell-Experiments#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- containers >= 0.6.0.1
- hashable

executables:
  Haskell-Experiments-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  Haskell-Experiments-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
